name: CI
on: [push]
jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN  }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm ci
      - run: npx nx format:check
      - run: npx nx affected:lint --base=origin/main~1 --head=origin/main
      - run: npx nx affected:test --base=origin/main~1 --head=origin/main
      - run: npm run build
      - name: Push client build to "client-build" branch
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: client-build
          FOLDER: dist/apps/client
          SQUASH_HISTORY: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: push server build to "server-build" branch
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: server-build
          FOLDER: dist/apps/server
          SQUASH_HISTORY: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
